# Generated by Django 5.2.9 on 2025-12-10 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Estación Río Norte', max_length=100)),
                ('codigo_identificador', models.CharField(help_text='ID único del Datalogger (ej: 21738)', max_length=50, unique=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('limite_oxigeno_min', models.FloatField(default=4.0, help_text='Alerta si baja de este valor')),
                ('limite_bateria_min', models.FloatField(default=11.5, help_text='Alerta si baja de este valor')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('danger', 'Peligro Crítico')], default='info', max_length=20)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='telemetria.estacion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador Global'), ('supervisor', 'Supervisor de Proyecto'), ('operador', 'Operador de Campo'), ('cliente', 'Cliente (Solo lectura)')], default='operador', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Para alertas SMS/WhatsApp', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('usuarios_asignados', models.ManyToManyField(blank=True, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='telemetria.proyecto'),
        ),
        migrations.CreateModel(
            name='DatosSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Fecha y Hora')),
                ('record_id', models.IntegerField(verbose_name='Número de Registro')),
                ('bateria_voltaje', models.FloatField(blank=True, null=True, verbose_name='Batería (V)')),
                ('ptemp_c', models.FloatField(blank=True, null=True, verbose_name='Temp. Interna (°C)')),
                ('oxigeno_disuelto', models.FloatField(blank=True, null=True, verbose_name='Oxígeno (mg/L)')),
                ('oxigeno_max', models.FloatField(blank=True, null=True, verbose_name='Oxígeno Máx')),
                ('oxigeno_tmax', models.DateTimeField(blank=True, null=True, verbose_name='Hora Oxígeno Máx')),
                ('porcentaje_oxigeno', models.FloatField(blank=True, null=True, verbose_name='% Oxígeno')),
                ('presion_oxigeno', models.FloatField(blank=True, null=True, verbose_name='Presión O2')),
                ('temperatura_agua', models.FloatField(blank=True, null=True, verbose_name='Temp. Agua (°C)')),
                ('conductividad', models.FloatField(blank=True, null=True, verbose_name='Conductividad')),
                ('salinidad', models.FloatField(blank=True, null=True, verbose_name='Salinidad (%)')),
                ('salinidad_max', models.FloatField(blank=True, null=True, verbose_name='Salinidad Máx')),
                ('salinidad_tmax', models.DateTimeField(blank=True, null=True, verbose_name='Hora Salinidad Máx')),
                ('solidos_disueltos', models.FloatField(blank=True, null=True, verbose_name='TDS')),
                ('densidad', models.FloatField(blank=True, null=True, verbose_name='Densidad')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH')),
                ('ph_max', models.FloatField(blank=True, null=True, verbose_name='pH Máx')),
                ('ph_tmax', models.DateTimeField(blank=True, null=True, verbose_name='Hora pH Máx')),
                ('orp', models.FloatField(blank=True, null=True, verbose_name='ORP (mV)')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='telemetria.estacion')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'ordering': ['-timestamp'],
                'unique_together': {('estacion', 'timestamp', 'record_id')},
            },
        ),
    ]
