# Generated by Django 5.2.9 on 2025-12-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0002_empresa_perfilusuario_avatar_alter_perfilusuario_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='telemetria.empresa'),
        ),
    ]
