# Generated by Django 5.2.9 on 2025-12-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0003_proyecto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plan',
            field=models.CharField(choices=[('gratuito', 'Plan Gratuito (Demo)'), ('basico', 'Básico'), ('estandar', 'Estándar'), ('pro', 'Profesional'), ('enterprise', 'Corporativo')], default='gratuito', max_length=20),
        ),
    ]
